theme: jekyll-theme-minimal
title: mytitle
description: mydescription
articles:
  - name: article1
    chapters:
      - name: chapter1
      - name: chapter2
  - name: article2
    chapters:
    - name: chapter1
